//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "ТабНомер as \'Таб номер\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "НомерПас as \'Номер пас\'",
            "СерияПас as \'Серия пас\'"})]
    [View("СотрудникиL", new string[] {
            "ТабНомер as \'Таб номер\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "НомерПас as \'Номер пас\'",
            "СерияПас as \'Серия пас\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private int fТабНомер;
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private int fНомерПас;
        
        private int fСерияПас;
        
        private IIS.Test_2.Должность fДолжность;
        
        private IIS.Test_2.Отдел fОтдел;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Имя CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Имя Get start)

                // *** End programmer edit section *** (Сотрудники.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Сотрудники.Имя Get end)

                // *** End programmer edit section *** (Сотрудники.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Имя Set start)

                // *** End programmer edit section *** (Сотрудники.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Сотрудники.Имя Set end)

                // *** End programmer edit section *** (Сотрудники.Имя Set end)
            }
        }
        
        /// <summary>
        /// НомерПас.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.НомерПас CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.НомерПас CustomAttributes)
        public virtual int НомерПас
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.НомерПас Get start)

                // *** End programmer edit section *** (Сотрудники.НомерПас Get start)
                int result = this.fНомерПас;
                // *** Start programmer edit section *** (Сотрудники.НомерПас Get end)

                // *** End programmer edit section *** (Сотрудники.НомерПас Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.НомерПас Set start)

                // *** End programmer edit section *** (Сотрудники.НомерПас Set start)
                this.fНомерПас = value;
                // *** Start programmer edit section *** (Сотрудники.НомерПас Set end)

                // *** End programmer edit section *** (Сотрудники.НомерПас Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Отчество CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Отчество Get start)

                // *** End programmer edit section *** (Сотрудники.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Сотрудники.Отчество Get end)

                // *** End programmer edit section *** (Сотрудники.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Отчество Set start)

                // *** End programmer edit section *** (Сотрудники.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Сотрудники.Отчество Set end)

                // *** End programmer edit section *** (Сотрудники.Отчество Set end)
            }
        }
        
        /// <summary>
        /// СерияПас.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.СерияПас CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.СерияПас CustomAttributes)
        public virtual int СерияПас
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.СерияПас Get start)

                // *** End programmer edit section *** (Сотрудники.СерияПас Get start)
                int result = this.fСерияПас;
                // *** Start programmer edit section *** (Сотрудники.СерияПас Get end)

                // *** End programmer edit section *** (Сотрудники.СерияПас Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.СерияПас Set start)

                // *** End programmer edit section *** (Сотрудники.СерияПас Set start)
                this.fСерияПас = value;
                // *** Start programmer edit section *** (Сотрудники.СерияПас Set end)

                // *** End programmer edit section *** (Сотрудники.СерияПас Set end)
            }
        }
        
        /// <summary>
        /// ТабНомер.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ТабНомер CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ТабНомер CustomAttributes)
        public virtual int ТабНомер
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ТабНомер Get start)

                // *** End programmer edit section *** (Сотрудники.ТабНомер Get start)
                int result = this.fТабНомер;
                // *** Start programmer edit section *** (Сотрудники.ТабНомер Get end)

                // *** End programmer edit section *** (Сотрудники.ТабНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ТабНомер Set start)

                // *** End programmer edit section *** (Сотрудники.ТабНомер Set start)
                this.fТабНомер = value;
                // *** Start programmer edit section *** (Сотрудники.ТабНомер Set end)

                // *** End programmer edit section *** (Сотрудники.ТабНомер Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Фамилия Get start)

                // *** End programmer edit section *** (Сотрудники.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Сотрудники.Фамилия Get end)

                // *** End programmer edit section *** (Сотрудники.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Фамилия Set start)

                // *** End programmer edit section *** (Сотрудники.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Сотрудники.Фамилия Set end)

                // *** End programmer edit section *** (Сотрудники.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Должность CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.Test_2.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Должность Get start)

                // *** End programmer edit section *** (Сотрудники.Должность Get start)
                IIS.Test_2.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (Сотрудники.Должность Get end)

                // *** End programmer edit section *** (Сотрудники.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Должность Set start)

                // *** End programmer edit section *** (Сотрудники.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Сотрудники.Должность Set end)

                // *** End programmer edit section *** (Сотрудники.Должность Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Отдел CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Отдел CustomAttributes)
        [PropertyStorage(new string[] {
                "Отдел"})]
        [NotNull()]
        public virtual IIS.Test_2.Отдел Отдел
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Отдел Get start)

                // *** End programmer edit section *** (Сотрудники.Отдел Get start)
                IIS.Test_2.Отдел result = this.fОтдел;
                // *** Start programmer edit section *** (Сотрудники.Отдел Get end)

                // *** End programmer edit section *** (Сотрудники.Отдел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Отдел Set start)

                // *** End programmer edit section *** (Сотрудники.Отдел Set start)
                this.fОтдел = value;
                // *** Start programmer edit section *** (Сотрудники.Отдел Set end)

                // *** End programmer edit section *** (Сотрудники.Отдел Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.Test_2.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.Test_2.Сотрудники));
                }
            }
        }
    }
}
